# Generated by Django 2.1.2 on 2019-01-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190114_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='qq',
        ),
    ]
