# Generated by Django 2.1.2 on 2019-01-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20190108_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_number',
            new_name='student_num',
        ),
    ]
