# Generated by Django 2.1.2 on 2019-01-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20190116_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='week_ord_res',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='what_day',
            field=models.IntegerField(default=1),
        ),
    ]
