# Generated by Django 2.1.2 on 2019-02-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20190116_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='yiqi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Instrument'),
        ),
    ]
