# Generated by Django 2.1.2 on 2019-01-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20190116_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='class1_available',
            new_name='class_ord',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='class2_available',
            new_name='fri_cls',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='class3_available',
            new_name='mon_cls',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='class4_available',
            new_name='thurs_cls',
        ),
        migrations.RemoveField(
            model_name='day',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='day',
            name='start',
        ),
        migrations.RemoveField(
            model_name='day',
            name='week_name',
        ),
        migrations.AddField(
            model_name='day',
            name='tues_cls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='wed_cls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='week_ord',
            field=models.IntegerField(default=1),
        ),
    ]
