# Generated by Django 2.1.2 on 2019-04-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20190309_1737'),
        ('tests', '0012_auto_20190310_1655'),
    ]

    operations = [
    ]
