# Generated by Django 2.1.2 on 2019-04-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_merge_20190406_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='capta',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
