# Generated by Django 2.1.2 on 2019-04-10 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_auto_20190406_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': '实验日期安排', 'verbose_name_plural': '实验日期安排'},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': '仪器', 'verbose_name_plural': '仪器'},
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={'verbose_name': '实验室', 'verbose_name_plural': '实验室'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '预约', 'verbose_name_plural': '预约'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
    ]
