# Generated by Django 2.1.2 on 2019-08-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_auto_20190410_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_num',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
